apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-fruits-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tomek-skrond/k8s-audit.git
    targetRevision: HEAD
    path: cloud/testing
  destination:
    server: https://kubernetes.default.svc
    namespace: fruitapp
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true