apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: prod-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.16.100-172.16.16.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
    name: l2-advert
    namespace: metallb-system
