Vagrant.configure("2") do |config|
  
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "worker-node" do |node|
    node.vm.box = "almalinux/9"
    # node.vm.box_check_update  = false
    node.vm.provider :virtualbox do |vb|
      vb.name = "worker-node"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "master-node" do |node|
    node.vm.box = "almalinux/9"
    # node.vm.box_check_update  = false
    node.vm.provider :virtualbox do |vb|
      vb.name = "master-node"
      vb.memory = 2048
      vb.cpus = 2
    end
  end
end