apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: prod-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.71.100-10.0.71.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
    name: l2-advert
    namespace: metallb-system
